version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/client/node_modules
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
